source 'https://rubygems.org'

gem 'rails', '4.2.1'

gem 'rails-api'

gem 'spring', :group => :development

gem 'pg'

gem 'active_model_serializers', '0.8.3'

gem 'httparty'

group :test do
  gem 'shoulda-matchers', require: false
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'rspec-rails', '~> 3.0.0'
  gem 'dotenv-rails'
end

